version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - npm install -g yarn
      - node --version
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - next build
      - yarn next export
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
