version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - next build
      - yarn next export
artifacts:
  files:
    - '**/*'
  base-directory: 'dist',