version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
      - npm install -g yarn
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn run build
      - yarn next export
  post_build:
    commands:
      - aws s3 cp index.html s3://naejango
      - aws cloudfront create-invalidation --distribution-id E3ODUFY373RJ9 --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'out'
