version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 18
      - npm install -g yarn
  pre_build:
    commands:
      - echo NEXT_PUBLIC_API_URL= ${API_URL} >> .env.production
      - echo NEXT_PUBLIC_KAKAO_REST_API_KEY= ${KAKAO_REST_API_KEY} >> .env.production
      - echo NEXT_PUBLIC_KAKAO_JS_KEY= ${KAKAO_JS_KEY} >> .env.production
      - echo NEXT_PUBLIC_AWS_REGION= ${AWS_REGION} >> .env.production
      - echo NEXT_PUBLIC_AWS_ACCESS_KEY_ID= ${AWS_ACCESS_KEY_ID} >> .env.production
      - echo NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY= ${AWS_SECRET_ACCESS_KEY} >> .env.production
      - yarn
  build:
    commands:
      - yarn run build
      - yarn next export
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id E3ODUFY373RJ9 --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: '.yarn'
cache:
  paths:
    - 'node_modules/**/*'
    - '.yarn/**/*',
    - '.next/cache/**/*'