version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install yarn...
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - next build
      - yarn next export
artifacts:
  files:
      - '**/*'
  base-directory: 'dist',
Properties:
  Environment:
    Image: "aws/codebuild/standard:5.0"