version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - next build
      - yarn next export
artifacts:
  files:
      - '**/*'
  base-directory: 'dist',