version: 0.1 # 임의의 버전 이름
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - yarn
  build:
    commands:
      - next build
      - yarn next export
  # npm 명령어는 정적 파일 생성을 위해 package.json에 작성한 scripts에 맞게 작성합니다.
artifacts: # CodeBuild의 output artifcats를 지정합니다.
  files:
      - '**/*'
  base-directory: 'dist'   # dist 디렉토리의 모든 파일이 해당됩니다.